---
- name: toptour
  hosts: toptour
  vars:
    project_name: toptour
    deploy_user: "{{ ansible_user }}"
    deploy_directory: /home/{{ ansible_user }}/{{project_name}}

    elasticsearch_backup_file: "../data/backup.tar.gz"
    elasticsearch_backup_location: "{{deploy_directory}}/data/backup"

    elasticsearch_backup_name: "toptour_backup"
    elasticsearch_snapshot_name: "snapshot_2"

    elasticsearch_host: "{{ansible_host}}"
    elasticsearch_port: 9200
    elasticsearch_server: "http://{{elasticsearch_host}}:{{elasticsearch_port}}"

    search_server: www.search.kartan.no
    server_name_line: "server_name {{search_server}}"
        
    restore_indices: true
    from_git: false
    
    nodejs_version: "4.x"

  tasks:
    - name: install git
      apt: pkg=git state=present
  roles:
    - role: geerlingguy.nodejs
      tags: 
        - javascript
        - nodejs
    - geerlingguy.java
    - toptour_elasticsearch
    - role: toptour_app 
      tags: 
        - javascript
        - app
    - nginx