---

  - name: Ensure bakcup folder exists
    file: path={{elasticsearch_backup_location}} state=directory mode=0777

  - name: Ensure elasticsearch is running
    service: name=elasticsearch state=started

  - name: Copy elasticsearch config file
    template: src=elasticsearch_config.j2 dest='/etc/elasticsearch/elasticsearch.yml'

  - name: Ensure elasticsearch is running
    service: name=elasticsearch state=restarted


  - name: Setup toptour client
      url={{elasticsearch_server}}/_snapshot/{{elasticsearch_backup_name}}
      method=POST
      status_code=200
      body_format=json

      body={{ lookup('template', 'backup_body.j2') | to_json }}
      # body="{{elasticsearch_backup_settings|to_json}}"
    when: restore_indices

  # - name: POST restore
  #   uri:
  #     url=https://10.0.0.116:9200/toptour
  #     method=POST
  #     status_code=200
  # #   when: restore_indices
  # - name: setup backup folder
  #   uri: 
  #     url=http://10.0.0.116/_snapshot/my_backup/snapshot_1/_restore
  #     url=http//10.0.0.116/toptour_backup
  #     method=POST
  #"{{ lookup('template', 'backup_body.j2') }}" 
  #     body_format=json
  #     status_code=200
  #     body= '{ "my_backup" ': {'type': 'fs', 'settings': { 'compress': 'true', 'location': '/mount/backups/my_backup' }}}